/**
 * ISO 8583:1993 Data Element definitions (DE1–DE128).
 *
 * format:
 *   "b"   – binary
 *   "n"   – numeric
 *   "a"   – alpha
 *   "an"  – alphanumeric
 *   "ans" – alphanumeric special
 *   "z"   – track data
 *   "x+n" – sign + numeric amount
 *
 * lengthType:
 *   "fixed"  – fixed length
 *   "LLVAR"  – 2-digit length prefix
 *   "LLLVAR" – 3-digit length prefix
 *
 * maxLength: max number of characters (or bytes for binary fields)
 */
export const FIELD_DEFINITIONS = {
   1: { de:   1, name: 'Secondary Bitmap',                            format: 'b',   lengthType: 'fixed',   maxLength: 8  },
   2: { de:   2, name: 'Primary Account Number (PAN)',                format: 'n',   lengthType: 'LLVAR',   maxLength: 19 },
   3: { de:   3, name: 'Processing Code',                             format: 'n',   lengthType: 'fixed',   maxLength: 6  },
   4: { de:   4, name: 'Amount, Transaction',                         format: 'n',   lengthType: 'fixed',   maxLength: 12 },
   5: { de:   5, name: 'Amount, Settlement',                          format: 'n',   lengthType: 'fixed',   maxLength: 12 },
   6: { de:   6, name: 'Amount, Cardholder Billing',                  format: 'n',   lengthType: 'fixed',   maxLength: 12 },
   7: { de:   7, name: 'Transmission Date & Time',                    format: 'n',   lengthType: 'fixed',   maxLength: 10 },
   8: { de:   8, name: 'Amount, Cardholder Billing Fee',              format: 'n',   lengthType: 'fixed',   maxLength: 8  },
   9: { de:   9, name: 'Conversion Rate, Settlement',                 format: 'n',   lengthType: 'fixed',   maxLength: 8  },
  10: { de:  10, name: 'Conversion Rate, Cardholder Billing',         format: 'n',   lengthType: 'fixed',   maxLength: 8  },
  11: { de:  11, name: 'System Trace Audit Number',                   format: 'n',   lengthType: 'fixed',   maxLength: 6  },
  12: { de:  12, name: 'Local Transaction Time',                      format: 'n',   lengthType: 'fixed',   maxLength: 6  },
  13: { de:  13, name: 'Local Transaction Date',                      format: 'n',   lengthType: 'fixed',   maxLength: 4  },
  14: { de:  14, name: 'Expiration Date',                             format: 'n',   lengthType: 'fixed',   maxLength: 4  },
  15: { de:  15, name: 'Settlement Date',                             format: 'n',   lengthType: 'fixed',   maxLength: 4  },
  16: { de:  16, name: 'Currency Conversion Date',                    format: 'n',   lengthType: 'fixed',   maxLength: 4  },
  17: { de:  17, name: 'Capture Date',                                format: 'n',   lengthType: 'fixed',   maxLength: 4  },
  18: { de:  18, name: 'Merchant Type',                               format: 'n',   lengthType: 'fixed',   maxLength: 4  },
  19: { de:  19, name: 'Acquiring Institution Country Code',          format: 'n',   lengthType: 'fixed',   maxLength: 3  },
  20: { de:  20, name: 'PAN Extended Country Code',                   format: 'n',   lengthType: 'fixed',   maxLength: 3  },
  21: { de:  21, name: 'Forwarding Institution Country Code',         format: 'n',   lengthType: 'fixed',   maxLength: 3  },
  22: { de:  22, name: 'Point of Service Entry Mode',                 format: 'n',   lengthType: 'fixed',   maxLength: 3  },
  23: { de:  23, name: 'Application PAN Sequence Number',             format: 'n',   lengthType: 'fixed',   maxLength: 3  },
  24: { de:  24, name: 'Network International Identifier',            format: 'n',   lengthType: 'fixed',   maxLength: 3  },
  25: { de:  25, name: 'Point of Service Condition Code',             format: 'n',   lengthType: 'fixed',   maxLength: 2  },
  26: { de:  26, name: 'POS PIN Capture Code',                        format: 'n',   lengthType: 'fixed',   maxLength: 2  },
  27: { de:  27, name: 'Authorization Identification Response Length',format: 'n',   lengthType: 'fixed',   maxLength: 1  },
  28: { de:  28, name: 'Amount, Transaction Fee',                     format: 'x+n', lengthType: 'fixed',   maxLength: 9  },
  29: { de:  29, name: 'Amount, Settlement Fee',                      format: 'x+n', lengthType: 'fixed',   maxLength: 9  },
  30: { de:  30, name: 'Amount, Transaction Processing Fee',          format: 'x+n', lengthType: 'fixed',   maxLength: 9  },
  31: { de:  31, name: 'Amount, Settlement Processing Fee',           format: 'x+n', lengthType: 'fixed',   maxLength: 9  },
  32: { de:  32, name: 'Acquiring Institution ID Code',               format: 'n',   lengthType: 'LLVAR',   maxLength: 11 },
  33: { de:  33, name: 'Forwarding Institution ID Code',              format: 'n',   lengthType: 'LLVAR',   maxLength: 11 },
  34: { de:  34, name: 'Primary Account Number Extended',             format: 'ns',  lengthType: 'LLVAR',   maxLength: 28 },
  35: { de:  35, name: 'Track 2 Data',                                format: 'z',   lengthType: 'LLVAR',   maxLength: 37 },
  36: { de:  36, name: 'Track 3 Data',                                format: 'z',   lengthType: 'LLLVAR',  maxLength: 104},
  37: { de:  37, name: 'Retrieval Reference Number',                  format: 'an',  lengthType: 'fixed',   maxLength: 12 },
  38: { de:  38, name: 'Authorization Identification Response',       format: 'an',  lengthType: 'fixed',   maxLength: 6  },
  39: { de:  39, name: 'Response Code',                               format: 'an',  lengthType: 'fixed',   maxLength: 2  },
  40: { de:  40, name: 'Service Restriction Code',                    format: 'n',   lengthType: 'fixed',   maxLength: 3  },
  41: { de:  41, name: 'Card Acceptor Terminal ID',                   format: 'ans', lengthType: 'fixed',   maxLength: 8  },
  42: { de:  42, name: 'Card Acceptor ID Code',                       format: 'ans', lengthType: 'fixed',   maxLength: 15 },
  43: { de:  43, name: 'Card Acceptor Name/Location',                 format: 'ans', lengthType: 'fixed',   maxLength: 40 },
  44: { de:  44, name: 'Additional Response Data',                    format: 'an',  lengthType: 'LLVAR',   maxLength: 25 },
  45: { de:  45, name: 'Track 1 Data',                                format: 'ans', lengthType: 'LLVAR',   maxLength: 76 },
  46: { de:  46, name: 'Additional Data - ISO',                       format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
  47: { de:  47, name: 'Additional Data - National',                  format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
  48: { de:  48, name: 'Additional Data - Private',                   format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
  49: { de:  49, name: 'Currency Code, Transaction',                  format: 'an',  lengthType: 'fixed',   maxLength: 3  },
  50: { de:  50, name: 'Currency Code, Settlement',                   format: 'an',  lengthType: 'fixed',   maxLength: 3  },
  51: { de:  51, name: 'Currency Code, Cardholder Billing',           format: 'an',  lengthType: 'fixed',   maxLength: 3  },
  52: { de:  52, name: 'Personal Identification Number Data',         format: 'b',   lengthType: 'fixed',   maxLength: 8  },
  53: { de:  53, name: 'Security Related Control Information',        format: 'n',   lengthType: 'fixed',   maxLength: 16 },
  54: { de:  54, name: 'Additional Amounts',                          format: 'ans', lengthType: 'LLLVAR',  maxLength: 120},
  55: { de:  55, name: 'Integrated Circuit Card (ICC) Data',          format: 'b',   lengthType: 'LLLVAR',  maxLength: 999},
  56: { de:  56, name: 'Reserved ISO',                                format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
  57: { de:  57, name: 'Reserved National',                           format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
  58: { de:  58, name: 'Reserved National',                           format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
  59: { de:  59, name: 'Reserved National',                           format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
  60: { de:  60, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
  61: { de:  61, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
  62: { de:  62, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
  63: { de:  63, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
  64: { de:  64, name: 'Message Authentication Code (MAC)',           format: 'b',   lengthType: 'fixed',   maxLength: 8  },
  65: { de:  65, name: 'Bitmap, Extended',                            format: 'b',   lengthType: 'fixed',   maxLength: 8  },
  66: { de:  66, name: 'Settlement Code',                             format: 'n',   lengthType: 'fixed',   maxLength: 1  },
  67: { de:  67, name: 'Extended Payment Code',                       format: 'n',   lengthType: 'fixed',   maxLength: 2  },
  68: { de:  68, name: 'Receiving Institution Country Code',          format: 'n',   lengthType: 'fixed',   maxLength: 3  },
  69: { de:  69, name: 'Settlement Institution Country Code',         format: 'n',   lengthType: 'fixed',   maxLength: 3  },
  70: { de:  70, name: 'Network Management Information Code',         format: 'n',   lengthType: 'fixed',   maxLength: 3  },
  71: { de:  71, name: 'Message Number',                              format: 'n',   lengthType: 'fixed',   maxLength: 4  },
  72: { de:  72, name: 'Message Number Last',                         format: 'n',   lengthType: 'fixed',   maxLength: 4  },
  73: { de:  73, name: 'Date, Action',                                format: 'n',   lengthType: 'fixed',   maxLength: 6  },
  74: { de:  74, name: 'Credits, Number',                             format: 'n',   lengthType: 'fixed',   maxLength: 10 },
  75: { de:  75, name: 'Credits, Reversal Number',                    format: 'n',   lengthType: 'fixed',   maxLength: 10 },
  76: { de:  76, name: 'Debits, Number',                              format: 'n',   lengthType: 'fixed',   maxLength: 10 },
  77: { de:  77, name: 'Debits, Reversal Number',                     format: 'n',   lengthType: 'fixed',   maxLength: 10 },
  78: { de:  78, name: 'Transfer Number',                             format: 'n',   lengthType: 'fixed',   maxLength: 10 },
  79: { de:  79, name: 'Transfer, Reversal Number',                   format: 'n',   lengthType: 'fixed',   maxLength: 10 },
  80: { de:  80, name: 'Inquiries Number',                            format: 'n',   lengthType: 'fixed',   maxLength: 10 },
  81: { de:  81, name: 'Authorizations, Number',                      format: 'n',   lengthType: 'fixed',   maxLength: 10 },
  82: { de:  82, name: 'Credits, Processing Fee Amount',              format: 'n',   lengthType: 'fixed',   maxLength: 12 },
  83: { de:  83, name: 'Credits, Transaction Fee Amount',             format: 'n',   lengthType: 'fixed',   maxLength: 12 },
  84: { de:  84, name: 'Debits, Processing Fee Amount',               format: 'n',   lengthType: 'fixed',   maxLength: 12 },
  85: { de:  85, name: 'Debits, Transaction Fee Amount',              format: 'n',   lengthType: 'fixed',   maxLength: 12 },
  86: { de:  86, name: 'Credits, Amount',                             format: 'n',   lengthType: 'fixed',   maxLength: 16 },
  87: { de:  87, name: 'Credits, Reversal Amount',                    format: 'n',   lengthType: 'fixed',   maxLength: 16 },
  88: { de:  88, name: 'Debits, Amount',                              format: 'n',   lengthType: 'fixed',   maxLength: 16 },
  89: { de:  89, name: 'Debits, Reversal Amount',                     format: 'n',   lengthType: 'fixed',   maxLength: 16 },
  90: { de:  90, name: 'Original Data Elements',                      format: 'n',   lengthType: 'fixed',   maxLength: 42 },
  91: { de:  91, name: 'File Update Code',                            format: 'an',  lengthType: 'fixed',   maxLength: 1  },
  92: { de:  92, name: 'File Security Code',                          format: 'an',  lengthType: 'fixed',   maxLength: 2  },
  93: { de:  93, name: 'Response Indicator',                          format: 'an',  lengthType: 'fixed',   maxLength: 5  },
  94: { de:  94, name: 'Service Indicator',                           format: 'an',  lengthType: 'fixed',   maxLength: 7  },
  95: { de:  95, name: 'Replacement Amounts',                         format: 'an',  lengthType: 'fixed',   maxLength: 42 },
  96: { de:  96, name: 'Message Security Code',                       format: 'b',   lengthType: 'fixed',   maxLength: 8  },
  97: { de:  97, name: 'Amount, Net Settlement',                      format: 'x+n', lengthType: 'fixed',   maxLength: 17 },
  98: { de:  98, name: 'Payee',                                       format: 'ans', lengthType: 'fixed',   maxLength: 25 },
  99: { de:  99, name: 'Settlement Institution ID Code',              format: 'n',   lengthType: 'LLVAR',   maxLength: 11 },
 100: { de: 100, name: 'Receiving Institution ID Code',               format: 'n',   lengthType: 'LLVAR',   maxLength: 11 },
 101: { de: 101, name: 'File Name',                                   format: 'ans', lengthType: 'LLVAR',   maxLength: 17 },
 102: { de: 102, name: 'Account Identification 1',                    format: 'ans', lengthType: 'LLVAR',   maxLength: 28 },
 103: { de: 103, name: 'Account Identification 2',                    format: 'ans', lengthType: 'LLVAR',   maxLength: 28 },
 104: { de: 104, name: 'Transaction Description',                     format: 'ans', lengthType: 'LLLVAR',  maxLength: 100},
 105: { de: 105, name: 'Reserved ISO',                                format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 106: { de: 106, name: 'Reserved ISO',                                format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 107: { de: 107, name: 'Reserved ISO',                                format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 108: { de: 108, name: 'Reserved National',                           format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 109: { de: 109, name: 'Reserved National',                           format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 110: { de: 110, name: 'Reserved National',                           format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 111: { de: 111, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 112: { de: 112, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 113: { de: 113, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 114: { de: 114, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 115: { de: 115, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 116: { de: 116, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 117: { de: 117, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 118: { de: 118, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 119: { de: 119, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 120: { de: 120, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 121: { de: 121, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 122: { de: 122, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 123: { de: 123, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 124: { de: 124, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 125: { de: 125, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 126: { de: 126, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 127: { de: 127, name: 'Reserved Private',                            format: 'ans', lengthType: 'LLLVAR',  maxLength: 999},
 128: { de: 128, name: 'Message Authentication Code (MAC)',           format: 'b',   lengthType: 'fixed',   maxLength: 8  },
};